import collections,hashlib,json,re,subprocess
from pathlib import Path
O=Path(__file__).parent;ROOT=Path('/home/dw/Projects/agent-sts2');A=json.load(open(O/'audit.json'));C=json.load(open(O/'changes.json'));F=json.load(open(O/'historical-facts.json'));L=json.load(open(O/'ledger-result.json'));M=json.load(open(O/'live-merge.json'));SL=json.load(open(O/'sl-summary.json'));RS=json.load(open(O/'rest-summary.json'));SS=json.load(open(O/'slice-summary.json'));base=json.load(open(O/'baseline-check.json'));title=(O/'changelog-title.txt').read_text().strip();stamp=subprocess.check_output(['date','+%Y-%m-%d %H:%M:%S %z'],text=True).strip();N='YLYLZWHA0GKU';commit=(O/'commit.txt').read_text().strip();P=ROOT/'paper/materials/experience-changelog-silent.md'
def tests(name):
 t=(O/name).read_text();return dict(tsc=0,vitest=0,files=sum(map(int,re.findall(r'Test Files\s+(\d+) passed',t))),cases=sum(map(int,re.findall(r'Tests\s+(\d+) passed',t))))
T=tests('test-source.log');assert T['files'] and T['cases'] and (O/'test-source.rc').read_text().strip()=='0'
def table(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(map(str,r))+' |' for r in rows])
def ev(eid):
 f=F[eid];return str(len(f['evidence']))+'/'+str(len(f['contradicting']))+'；'+','.join('A'+str(k)+':'+str(v) for k,v in f['asc_support'].items())
parts=[title,'### 来源',f'''- 记录时间{stamp}。只读notes/lessons.md:5346及紧后本局记录，未见本局追加勘误；runs.character=SILENT、A10、F45败，未跳过。last_seen按notes/run-1007-0832-YLYLZWHA0GKU.md取2026-10-07。开工exp-silent干净，git merge --no-edit main成功、无冲突；先读README、最新STATE、决定末尾、学习协议、首次构建与最近两次方法。独立执行，不派agent、不运行play或boss模拟池；数据与工具均nice19。
- 截至{A['cutoff']}，85静默完局；A0—A10局数7/3/2/1/4/1/11/7/1/3/45。旧1265房74实死，加新19房1死＝1284房75死；A10四十五局570房45死。MCCK2602T1SR仍只进数字；无character旧局、其他角色、进行中与后续局排除。
- 按12位run id抽655 decisions、42 brain、8 run-plans、2 sl-attempts；复盘所记9 run-plans与本次原日志rg的8条有一行差异，以实际抽取文件为准。states按时间二分seek后流读683静默帧，逐条ts/observed_ts核对655决策；同窗deepseek-reasoning为0，实际42次大脑全Codex。f65cbfac+dirty不能复原为干净源码。原片段、脚本、逐局重算、历史机制与完整切片在learner/runs/20261007-091304-experience-update。
- 口径沿第67节：首COMBAT→同房最终尝试末结算HP净损，实死单列、负回复保留；Monster走廊和Unknown问号分开；入场HP/当时max HP分<25%、[25%,40%)、[40%,60%)、≥60%。REST/SHOP/普通EVENT按源入血关联下一更高层第一战、Ancient排除；多源可同战，回血后下一战按run/floor去重，TD1同房重启仍一房。读档不算回血，死亡剩余HP截断不当完整攻击需求，未结算毒不预支。
- 重执行旧84局原分析脚本：七数组、全部血档/源节点、回血、SL逐行一致。数字没有对不上的旧批次项；本局F39 T2复盘“3毒扣9、仍余3”与原始状态冲突：00:27:50.832Z结束前185血/3毒，00:27:58.056Z新T3为179血/6毒；毒实际3+2+1=6，第二毒雾使下一轮补6。00:28:00.124Z带毒刺击才6→9毒，随后突然一拳后154血；不能把后续9毒/行动后HP误作T2末毒结算。原复盘保留，本节按原日志更正。旧毒雾lesson同时写40支持与n=39，本次统一到41。
- 开工137 active/49709字<55000，无强制压缩。新增1、更新9（全部补非药水证据、只改数字0）、退役0；active138/49357字。九条旧逐局叙述压短为机制和一两个案例，旧完整文字留experience-before.json；没有合并条目。potion:*和general:potion逐对象保持，其他含药旧句逐字保持，无新用药规则。机制[0,20]，路线/休息/构筑观察[8,20]，无新的进阶策略反例。初稿触媒旧药句前文局号压缩时丢失，定稿只补TU3XB4CAEDAW/A10旧例标记，原药句一字未改；9fad69d7初稿提交/测试/11行proposed保留，唯一第68节引用最终提交。''','### 对照数据检查的主题']
themes=[('旧基线/角色','旧84局七数组/血档/节点/回血/SL一致；85局1284房75实死','统计只用静默，局/房/SL尝试分账'),('纸伤难愈2','历史30局遭遇、17局同回合上限下降帧；纳证K367 A1、9YBK A4、YLY A10三局；新T2五漏70→60，T3两漏60→56','每次未挡住攻击降2；不外推其他层数'),('毒雾启动','F45 T1/T2各建立3；T2各3共9、T3各8共24；死亡各7毒未结算','能力建立不即时加毒；累计毒实伤33'),('触媒复盘更正','F39 T2结束前敌185/3毒，下轮179/6毒，实际扣6；升级建2层','3+2+1，与毒雾下一轮补6分账；本局F33/F45未施触媒'),('余像','F33 T4建1；T8双防御10+五出牌被动5=15，对14攻击零损，2血撑至T9','建立及实际施放次数验收，F45未施不算'),('预判敏捷','F45 T2两临时增益各2、生存者8→10；T3归零、防御5+触不可及9=14','临时敏捷仅本轮，非永久挡'),('力量/虚弱','卷轴2力双击6×2→8×2；突然一拳虚弱8×2→6×2；三敌40攻/10挡损30','逐段力量/虚弱分核；T3的48攻/14挡需34、11血差23'),('尖啸','F33 T1各−6、T2恢复0；T2的15挡损11；F17亦实际施放','临时减力不关后续成长，不定单卡胜因'),('大衣标记/路线','F35/F38敌均1HP零损，F39法官56→17；F44 Unknown损12，F45未标记卷轴41→0','无精英不保证零损，一血收益只归覆盖房'),('实际回血/未来营火','八火四回血四锻造；33→54、26→62、53→70、17→53，共110；F43选锻造53血，F47未到','boss70投影依赖未来回血，不当当前HP；未选替线无受控因果'),('构筑输出','F33需428，T9清、70→2；F45需140、三轮扣40+23+39=102、余38，四张核心未施','取得/到手/施放/建立/结算分别核，不预支能力或余毒'),('SL对照','本局两boss首试均won，没有attempt≥2；全史75场328次26赢，A10 42场187次14赢不变','没有新同抽牌多试对照，不新增boss/精英打法'),('时钟/模拟','F16原始1000样本胜率0.975、校准0.9509，赢损中位31/实损21；F43原始536样本0胜、校准0.0474，三幕boss未到','21/31不是时钟输出比，未抵达和校准不当实战胜率；其他时钟字段未记录')]
parts+=[table(['主题','数据','结论'],themes),'七数组重算：',table(['数组','改前','改后','旧行一致'],[(k,v['before'],v['after'],'是') for k,v in base.items()]),'A0—A9全部非空格与第67节一致；完整各阶血档/局号/损值保存在audit.json。死亡率以房为分母，活场净损中位排除实死。A10全部非空格：',table(['幕','房型','血档','房/局','死/率','活场净损中位'],[(r['act'],r['type'],r['band'],f"{r['n']}/{r['runs']}",f"{r['deaths']}/{r['deaths']/r['n']:.2%}",r['median_win']) for r in A['bands'] if r['asc']==10 and r['n']]),'A10源节点到下一实战（源血档、同战可多源；Ancient排除）：',table(['幕','源','血档','源节点/不同战','死/率','活战净损中位'],[(r['act'],r['screen'],r['band'],f"{r['n']}/{r['unique_fights']}",f"{r['deaths']}/{r['deaths']/r['n']:.2%}",r['median_win']) for r in A['transfers'] if r['asc']==10 and r['n']]),'各进阶分母（不把SL尝试当局）：',table(['进阶','局','战房/死','火/回血/非回血','实回血','后战/死/活损中位','SL场/尝试/赢尝试'],[(f"A{r['asc']}",r['runs'],f"{sum(f['asc']==r['asc'] for f in A['fights'])}/{sum(f['death'] for f in A['fights'] if f['asc']==r['asc'])}",f"{r['rests']}/{r['heal']}/{r['smith']}",sum(r['gains']),f"{r['nexts']}/{r['deaths']}/{r['median']}",f"{sl['fights']}/{sl['attempts']}/{sl['wins']}") for r,sl in zip(RS,SL)]),'- 低血不同节点旧例重核：MGA0CZDDKC0P A10休息22→43后Monster损17活，4D4J8USKCPAV休息1→22后Monster损1活；D4LJ9QMGFB8Q事件13、BVF22RSFVBS9事件21后走廊死。新局F40枕头休息17→53后下一战Unknown损12活；F43升级后下一战也为该战、多源关联不是两场。敌人/构筑/间隔混杂，只有观察。全史75场328次26赢不变；沿旧受控限制，首抽序同也不等同回合到手或单变量，旧explore/sl_explore/decisions.sl_attempt/draws完整留盘，本次没有赢的重打可分析。','### 经验库自己带偏或写了没被执行的地方','''- 42 brain原始engine全Codex、同窗DeepSeek推理0；未找到明确引用旧经验id并造成反向结果的原话，不由死亡自动登记策略repeat。以下保留决策原话，英语仅用于原样引证。
- F6：“Second Noxious Fumes strengthens scaling and multi-enemy damage, with a substantial modeled boss improvement; other rewards offer less for this poison deck.”F17：“After Image adds efficient recurring block while poison scales, synergizes with shivs and draw, and directly addresses the deck’s defensive weakness.”两毒雾与余像确实取得，但F33到T4才建立余像、70→2；F45余像未施，取得不能当防御收益。
- F20：“Free temporary dexterity strengthens multiple block cards and synergizes with After Image; defense matters more than another slow poison power.”F45预判的2敏捷确给生存者多2挡，次轮撤回，不能从这句外推常驻挡或替牌胜因。
- F43：“Upgrade Prowess for lasting strength and dexterity across boss phases. Current 53 HP supports taking this improvement; reserve the final campfire for healing.”升级已执行，非凡技艺至死亡未施，F47未到；不能把未来回血或能力正力敏当已取得收益，也没有未选回血的整场胜线证明锻造错。
- F34：“大衣免除多场战损，揭晓标记后优化路线。”标记房F35/F38零损兑现，F45未标记，不能把局部效果覆盖全部走廊。''','### 机制推理']
mechs=[('纸伤难愈2','漏伤攻击每次降2上限，双击按漏伤次数；只限2层，与当前血/挡合核。',ev('silent-scroll-paper-cuts-unblocked'),'K3676LU8B0UH A1 F35 14挡后上限77→73；YLYLZWHA0GKU A10 F45五漏70→60、两漏60→56','silent-scroll-paper-cuts-unblocked'),('毒雾轮初增长','普通/升级2/3层，下一轮才施毒；单次结算补a净增a−1，头骨/触媒/剩血独立核。',ev('silent-noxious-fumes-growth'),'YLYLZWHA0GKU F45双雾3→6，实际9+24毒、死亡各7未兑；F33到T9毒杀428','silent-noxious-fumes-growth'),('触媒额外结算','k层至多k+1次、每次减1；k=2且p≥3为3p−3，不倍增层数。',ev('silent-accelerant-triggers'),'YLYLZWHA0GKU F39 T2的3毒185→179扣6，下轮补6；ZZMYZ5UBCG72 A2三触媒15毒扣54','silent-accelerant-triggers'),('余像逐牌被动挡','建立后每次实际出牌1挡，重放亦触发，脆弱不折被动；未建不计。',ev('silent-afterimage-per-card-block'),'YLYLZWHA0GKU F33 T8双防御10+五出牌5=15挡对14，2血撑到T9；F45未施','silent-afterimage-per-card-block'),('预判临时敏捷','建2/4临时敏捷逐挡牌兑现，次轮撤回，不追補旧挡；被动独立。',ev('silent-anticipate-temporary-dexterity'),'YLYLZWHA0GKU F45 T2生存者8→10、T3防御5与触不可及9仍14','silent-anticipate-temporary-dexterity'),('逐击力量/虚弱','每击加现场力量、虚弱逐击取整，段数放大收益；独立成长继续。',ev('silent-strength-weak-observation'),'YLYLZWHA0GKU F45卷轴2力双击12→16；虚弱16→12，三敌仍40攻','silent-strength-weak-observation'),('尖啸临时减力','普通/升级减6/8，当轮逐击核、次轮恢复，不能关后轮成长。',ev('silent-piercing-wail-temporary-strength'),'YLYLZWHA0GKU F33 T1双蟹−6，T2恢复0、15挡仍损11；KQQELQSZ382Z末T5零损/T6损5','silent-piercing-wail-temporary-strength'),('能力组合兑现观察','建立/结算时点与可活轮限定真实攻防；持有未施、死亡余毒不计，未控胜因。',ev('silent-deck-burst-observation'),'YLYLZWHA0GKU F33 70→2到T9清428；F45核心四张未施、实扣102/140余38','silent-deck-burst-observation')]
parts+=[table(['机制','推理','证据（支持/反例局数、进阶）','典型案例','进了哪个条目'],mechs),'- 所有12位证据/反例局号及进阶见经验JSON与historical-facts.json。毒雾/触媒/余像/预判/尖啸纳证局全部核到实际施放；全历史实际施放分别46局468次、35局297次、22局181次、14局101次、50局380次，纳证41/29/17/12/39局不是全部遭遇分母。纸伤全历史30局遭遇、17局有同回合上限下降帧，只把三局明确案例纳入证据；更早K367 A1使原账本0221首证9YBK A4得到追加更正，prior仍unknown，不删原行。力量与构筑是综合观察，不能把81/80局当每个子公式都有独立实验。败局中机制成立不作反例，无新喝药规则。','### 新增','- silent-scroll-paper-cuts-unblocked（hallway:SCROLL_OF_BITING）：3支持0反例、med、[0,20]，只确认纸伤难愈2按漏伤击数降上限。来源silent-0221，首证更正K3676LU8B0UH/A1、9YBK A4及新局A10；没有额外bug条目。','### 更新',table(['条目','支持局数','字符改前→后','变化'],[(d['id'],f"{d['n_before']}→{d['n_after']}",f"{d['chars_before']}→{d['chars_after']}",'补非药水证据、压短旧案例') for d in C['details']]),'- 9条全补证，纯数字0。毒雾正文旧n=39统一到41；触媒新案例以日志扣6/下轮6毒更正复盘扣9/余3，纸伤首证追加更正。旧药句逐字保持，不修改药水对象；没有合并，逐局完整原文/明细保留。','### 退役','- 无；未发现反例多过支持，真实机制不因模型bug退役，本次没有代码修复。','### 和手写知识及代码冲突','- 静默其他六份boss-damage/room-costs/monster-records/outcome-stats/fight-value/fight-value-gates均为生成数据，没有手写文件需改删。各文件哈希/生成口径见other-knowledge.json；刷新截止、首帧/战后回复、重复房窗与本次去重口径分别核，不把截止较旧或不同分母当数据无效；本批未发现需覆盖数据的实质矛盾。common只定向读卷轴、法官和双蟹的招式/增益；角色经验支持仍全静默，未搬其他角色知识。','- PAPER_CUTS_POWER已在combat-plan已建模名单及未挡惩罚启发式；这一启发式不当作真实掉血/上限公式。POISON_POWER模型与覆盖声明缺口列下节，本任务不改代码手写知识或铁甲行为。','### 代码问题（不给 DS）','''- silent-0216既有bug/repeat保留：F45 T2突然一拳实际8伤，选线题按逐击八折算6，预测21总伤/实际23；实际损30一致。本分支开工基线combat-plan已知名单漏POISON_POWER，turn-solver保留未知敌增益攻击×0.8；等待锁期间live已在14364072/DC899F95上线fix42，combat-plan:81现已声明POISON_POWER覆盖，不把旧基线缺口冒称当前生产未修bug。PAPER_CUTS已在名单，与毒折扣分账；不能把少报2归为死亡全部原因。本任务不修代码，不新增重复条目、不改bug状态。
- 首次排队合入在最终文本重测期间取得锁，被test-source.rc=pending的前置断言停止；未提交刷新、未进入merge，原initial-live-flow.log保留。这属本任务流程保护，不是游戏或测试失败。最终提交/账本就绪后重新走锁内流程。
- F45 T3代码least-loss预计11−34=−23，与14挡对48攻击的完整需求34一致；死亡实际只扣余血11，与完整损34分列。招架盾随机落点与实体总伤分列，不推出另一目标顺序胜线。
- 未记录：未选构筑/回血/路线和首杀另一卷轴的受控整战结果、重问后整条原最优线完整执行率、boss逐轮需伤/估伤及实际/时钟估值比。不补造，不把兼容DeepSeek计数当真实回退。''','### 测试',f"- 源tsc0、vitest0、{T['files']}文件{T['cases']}例，初稿与补回触媒旧局号后的定稿两轮均通过，均216文件2308例；非失败重跑，原结果留test-source-initial.log。JSON、证据角色/12位/n/置信度/进阶/字数、旧基线七数组/血档/源节点/回血/SL、原始状态匹配、历史机制实际卡牌、旧药对象/分句、git diff --check及提交前gitleaks通过。源码/测试预算/依赖/生成器均未改。",'- 只经learner/ledger.py/by=learner:experience-update，proposed '+','.join(L['proposed'])+'；add/retired无、check0。10个经验条目都有去向来源；0221追加K367并更正first_run/asc/prior_note，prior=unknown及claim/旧证据/旧历史保持。纯bug0216和未纳复盘项不改，未写accepted/shipped。主目录本节和账本只追加不提交，由调用方提交。',f"- live合入结果（未取得锁、只读重叠预检）：{M.get('reason','已合入并自测通过')}。刷新提交{M.get('refresh_commit')}；合前{M.get('base')}；实际合入{M.get('merged')}。不同知识blob重叠：{','.join(M.get('conflicting_overlap',[])) or '无'}。原预检/保存点见live-merge.json、readonly-preflight.json；source-final-ready写入资格已撤销，排队操作即使稍后取得锁也会在任何live写入前被断言禁止，停止时未进入实际合并、没有覆盖刷新知识；合后检查/上线版本结果按live-merge.json登记。交本批handoff-ops.md与experience-done通知运维据实际发布登记shipped或兜底，完整外部测试交调度器。不停对局、不运行play、不推送。",'### 切片大小','- 固定种子20260929，从截至新局全部静默状态、按state.run.character_id=SILENT筛最高A9/A10，各20状态×COMBAT/REWARD/MAP/EVENT/REST/SHOP＝240配对。官方knowledge-slice.ts/CHARACTER=silent/setExperienceForTests，只换经验JSON，其他角色未读；common与结果表冻结，完整manifest/原切片留盘。',table(['进阶/界面','改前中位/最大（字）','改后中位/最大（字）','配对增量中位'],[(r['sample'].removeprefix('sample-'),f"{r['before_median']}/{r['before_max']}",f"{r['after_median']}/{r['after_max']}",r['delta_median']) for r in SS['rows']]),f"- 配对增量中位{SS['delta_median']}字、最大增量{SS['delta_max']}；总体中位{SS['median_before']}→{SS['median_after']}、最大{SS['max_before']}→{SS['max_after']}字。active137→138、49709→49357字，高68中44低26；A8 131条46250字、A9 132条46549字。需要Roy定的知识事项：无。"]
section='\n\n'.join(parts)+'\n';(O/'changelog-section.md').write_text(section)
assert title not in P.read_text();before=P.read_bytes();(O/'changelog-prefix.json').write_text(json.dumps(dict(bytes=len(before),sha256=hashlib.sha256(before).hexdigest()))+'\n')
with P.open('a') as h:h.write('\n'+section)
assert P.read_bytes()[:len(before)]==before
(O/'source-tests.json').write_text(json.dumps(T)+'\n');print('追加第68节',len(section),'字；旧前缀逐字不变')
