import json,re,subprocess
from pathlib import Path
O=Path(__file__).parent;ROOT=Path('/home/dw/Projects/agent-sts2');LIVE=ROOT/'.worktrees/live';M=json.load(open(O/'live-merge.json'));C=json.load(open(O/'changes.json'));L=json.load(open(O/'ledger-result.json'));assert M['merged'] and M['test_rc']==0 and L['check']==0
def git(*a):return subprocess.check_output(['git','-C',str(LIVE),*a],text=True).strip()
paths=['paper/materials/decision-log.md','eval/versions.json'];assert not git('diff','--cached','--name-only') and not git('diff','--name-only','--',*paths)
versions=json.load(open(LIVE/paths[1]));name='S1.exp68';assert not any(v['name']==name for v in versions['versions']);stamp=subprocess.check_output(['date','+%Y-%m-%d %H:%M'],text=True).strip()
message=f'Codex学习者经验自测后上线：静默经验{C["old_version"]}→{C["version"]}，源{M["source_commit"]}→实际live {M["merged"]}，eval {name}。来源notes/lessons.md:5346的YLYLZWHA0GKU SILENT A10及历史静默；条目'+','.join(C['added']+C['updated'])+'；纸伤首证K3676LU8B0UH/A1、9YBKCNBFP0X5/A4、新局A10，其他证据见experience.json；账本'+','.join(L['proposed'])+f'只CLI proposed/check0，交运维核实际合入后登记shipped。旧84局七数组/血档/源节点/回血/SL全部复算一致；85局1284房75死、A10四十五局570房45死。新增1更新9（全补证、只数字0）退0、active138/49357字；纸伤2按漏伤次数降上限，毒雾/触媒/余像/临时敏与逐击力量及未来回血分账。F39 T2原日志185→179/3毒、下一轮补6为6毒，更正复盘扣9/余3；纸伤0221首证更正K367/A1、prior unknown保留。源及合后固定沙箱tsc/vitest0，完整外部交调度器；无源码、生成器、手写知识、其他角色或新用药规则改动。主目录本节和账本只追加，由调用方提交；本批handoff-ops.md和experience-done通知运维。'
with (LIVE/paths[0]).open('a') as h:h.write('\n- '+stamp+' '+message+'\n')
versions['versions'].append(dict(name=name,family='Silent',commit=M['merged'],source=f'decision-log {stamp}（静默经验2026-10-07.14，源{M["source_commit"]}；YLYLZWHA0GKU A10与历史静默，新增1更新9退0、138 active/49357字；纸伤2与毒/临时敏机制、路线未来回血分账，源/合后沙箱tsc/vitest0，账本11项proposed交运维登记shipped。）'))
(LIVE/paths[1]).write_text(json.dumps(versions,ensure_ascii=False,indent=2)+'\n');git('add',*paths);git('diff','--cached','--check');patch=O/'release.patch';patch.write_text(git('diff','--cached','--binary')+'\n')
with (O/'gitleaks-release.log').open('w') as h:subprocess.run(['nice','-n','19','/home/dw/.local/bin/gitleaks','dir','--redact','--no-banner',str(patch)],stdout=h,stderr=subprocess.STDOUT,check=True)
git('-c','user.name=dwroy','-c','user.email=roy.dongwei@gmail.com','commit','-m','Record Silent experience 2026-10-07.14 deployment','-m','Co-Authored-By: Codex GPT-6 <noreply@openai.com>');M.update(eval_version=name,release_commit=git('rev-parse','HEAD'),release_time=stamp);(O/'live-merge.json').write_text(json.dumps(M,ensure_ascii=False,indent=2)+'\n');print('上线登记',M['release_commit'],name)
