import collections,hashlib,json,re,statistics,subprocess,sys
from pathlib import Path
O=Path(__file__).parent.resolve();ROOT=Path('/home/dw/Projects/agent-sts2');load=lambda f:json.load(open(O/f));A=load('audit.json');U=load('update-summary.json');C=load('changes.json')['entries'];H={x['id']:x for x in load('historical-mechanism-summary.json')};SL=load('sl-summary.json');RE=load('rest-summary.json');M=load('ledger-map.json');L=load('ledger-results.json');P=load('proposal-ids.json');V=load('live-merge.json');SS=load('slice-summary.json');T=load('test-results.json');heading=(O/'changelog-heading.txt').read_text().strip();stamp=subprocess.check_output(['date','+%Y-%m-%d %H:%M:%S %Z'],text=True).strip();R=load('run-metadata.json');cases=[f for f in A['fights'] if f['run']=='M0GY0A4M2F7H'];DS=[json.loads(x) for x in (O/'M0GY0A4M2F7H/decisions.jsonl').open()];ST=[json.loads(x) for x in (O/'M0GY0A4M2F7H/states.jsonl').open()];brain=[json.loads(x) for x in (O/'M0GY0A4M2F7H/brain.jsonl').open()]
lines=['## '+heading,'','### 来源','', '- 记录时间'+stamp+'；经验版本日期取自10-08 23:50构建时date，跨日后仍保留2026-10-08.28。只读根notes/lessons.md:6354静默猎手M0GY0A4M2F7H；节后无本局勘误。runs.jsonl:627核SILENT/A10/F17败，无角色跳过；运行9949a5de+dirty完整源码未记录。', '- exp-silent开工干净，git merge --no-edit main无冲突快进至7984703d；已读README/最新STATE/decision-log、学习协议/代码提案、首次构建/最后两节方法及静默109/110节、账本README。独立执行、不派agent、不联网/不运行play或模拟池、不改打法源码/其他角色知识；临时文件只在本scratch，抽取nice19单进程、沙箱1worker。',f'- 按局号抽{len(DS)}决策、{len(brain)}大脑请求及6条SL，states/reasoning按决策UTC窗二分字节seek流读，{len(ST)}状态核run_id和state.run.character_id=SILENT；窗14:09:07.281Z—14:33:59.374Z。18请求全Codex，DeepSeek实际推理0，兼容ds_*名字不证实际引擎。原帧/偏移/提案/核验均留scratch。',f'- 全引擎学习观察截至{A["cutoff"]}共{len(R)}静默完局、{len(A["fights"])}独立房、{sum(f["death"] for f in A["fights"])}实死，分阶{dict(sorted(collections.Counter(r["ascension"] for r in R).items()))}；除新局外145局只进数字/历史验证。排缺character旧铁甲、其他角色、进行中和切点之后，不称纯Codex爬塔战绩。','- 口径沿上一节：战内净损=首COMBAT入口HP−同房最后尝试退出HP，含自损/回复/负值，不作敌毛伤；实死单列，前五SL判死截断不当实死。走廊只Monster，Unknown问号另算；血档<25%、[25%,40%)、[40%,60%)、≥60%。REST/SHOP/普通EVENT入口血关联下一更高层首战，排Ancient；多节点可重复关联，回血后战去重，营火房/动作分列，SL同房六试计一房。','- 旧145局七数组、全部血档/节点转移、回血及SL逐行复算一致：2101房/2004节点后战/907休息/47403牌动作/13503结束轮/866尝试/3960同族帧，原基线无漂移。加新9房/6尝试；585项原帧/经验字段/历史钓鱼竿核验通过，681段静默主题复盘与完整本角色日志交叉复核。滑溜攻击/毒限伤/力量成长另做全支持局逐帧核验，不把持有或动作出现自动当整条支持。',f'- 新增0、更新8（8加证据、0只改数字）、退役0；active186→186，正文50783→{U["chars"]}字符，低于55000压缩线/60000预算。没有预算合并/退役/压缩；重复主题并入原条目，逐轮细节留复盘和本报告。','','### 对照数据检查的主题','','| 主题 | 数据 | 结论 |','| --- | --- | --- |']
for c in C:
 e=c['after'];lines.append(f'| {e["id"]} | {e["n_support"]}支持/{e["n_contradict"]}反例；分阶{H[e["id"]]["by_asc"]}；账本'+','.join(M[e['id']])+' | '+e['lesson']+' |')
lines+=['','以下按进阶/幕/实际房型/首战入口血档列战斗；n为独立房、同局可多房，死亡率=实死房/n；活战净损中位含负值，不作敌总伤。','','| 进阶 | 幕 | 房型 | 血档 | 房数/局数 | 实死/率 | 活战净损中位 |','| --- | --- | --- | --- | --- | --- | --- |']
for b in A['bands']:
 if b['n']:lines.append(f'| A{b["asc"]} | {b["act"]} | {b["type"]} | {b["band"]} | {b["n"]}/{b["runs"]} | {b["deaths"]}/{b["deaths"]/b["n"]*100:.2f}% | {b["median_win"]} |')
lines+=['','非战节点入口血关联下一更高层首战；同一战可对应多个节点，分母不是路线随机实验。问号实际战另在Unknown中；普通EVENT排Ancient。','','| 进阶 | 幕 | 节点 | 入口血档 | 节点数/独立后战/局数 | 实死/率 | 活后战净损中位 |','| --- | --- | --- | --- | --- | --- | --- |']
for b in A['transfers']:
 if b['n']:lines.append(f'| A{b["asc"]} | {b["act"]} | {b["screen"]} | {b["band"]} | {b["n"]}/{b["unique_fights"]}/{len(set(x["run"] for x in b["cases"]))} | {b["deaths"]}/{b["deaths"]/b["n"]*100:.2f}% | {b["median_win"]} |')
lines+=['','| 进阶 | 局数 | 独立营火/回血动作/其他动作 | 实回 | 去重后战/实死 | 活后战损中位 |','| --- | --- | --- | --- | --- | --- |']
for r in RE:lines.append(f'| A{r["asc"]} | {r["runs"]} | {r["rests"]}/{r["heal"]}/{r["smith"]} | {sum(r["gains"])} | {r["nexts"]}/{r["deaths"]} | {r["median"]} |')
lines+=['','SL仅同房多次尝试算重打，实际赢次与判死截断分开，非独立样本。','','| 进阶 | 重打房 | 尝试 | 赢次 |','| --- | --- | --- | --- |']
for r in SL:lines.append(f'| A{r["asc"]} | {r["fights"]} | {r["attempts"]} | {r["wins"]} |')
lines+=['','A10墨影策略支持3局/3场18试0赢，各五次判死读档、仅末次实死；未记录赢的那次，不能归胜运气。M0GY0A4M2F7H第2/3与第4试T9同19血/敌97及手能底板，SL防御+换打击、保突然一拳，整轮净清19→25、损0→9，第四次T10判死；两线五轮均24/24死、整场估0.7%→0%。这是同盘局部血价，后续抽牌等仍变，不当独立整场因果。末试T3换线估2.2%→0.7%，药序/后继亦变，实多损5、多净清1。无整场保血胜例，不拟统一禁攻或喝留门槛。','','本局逐房资源（同房六试不重复独立房）：','','| 层 | 房型/敌人 | HP进→出 | 净损 | 实死 |','| --- | --- | --- | --- | --- |']
for f in cases:lines.append(f'| {f["floor"]} | {f["type"]}/'+','.join(f['enemies'])+f' | {f["hp"]}/{f["max_hp"]}→{f["last_hp"]}/{f["max_hp"]} | {f["loss"]} | {f["death"]} |')
lines+=['','八胜净耗83；开场56−83+三火63−事件7=29进boss，F12→13→14→15实际52→31→11→8，F16回到29。营火及SL恢复分账，不把五次恢复当额外回血。boss六次截断/末态HP3/4/4/10/1/0、敌113/70/65/72/64/126，首五未执行结算不补算；末T7完整需损32−20=12、现8只扣到0，存活至少差5血，而敌尚126不当差5伤击杀。','独立取得4瓶：癫狂之触/能量/力量/无色；实饮9次含SL后重饮5，未见弃药。F6两药已饮，boss无色六次均取闪亮，末次未打且T6弃掉，不预支药牌收益。没有单改饮用时点/留药的受控整场结果。','','### 经验库自己带偏或写了没被执行的地方','','- 实际DeepSeek请求/推理0，无DeepSeek引条目原话；Codex/Jev题面保留，未记录具体经验id导致选择的因果链。']
for floor in [7,12,16]:
 d=next(x for x in DS if x['floor']==floor and x['label']=='rest/plan');lines+=['- F'+str(floor)+'实际理由原文：'+json.dumps(d['rationale'],ensure_ascii=False)+'。']
lines+=['- F12的“three fights remain”已经指出沿路战斗，实回52兑现、条件boss64未兑现（实际29）；不能由单次差额归因全部同模型误差，F7后来改线/事件/新牌亦变。F16条件29与实际29一致；前胜并不等零资源代价。','- 第4试T9原回答防御+与突然一拳，实际SL改打击；末试T3原回答与替线/药序分开，不把rollout_best_chosen回答字段82.61%当完整实际执行最优比例。无因经验文字单独造成错选的证据。','','### 机制推理','','| 机制 | 推理 | 证据（支持/反例局数、进阶） | 典型案例 | 进了哪个条目 |','| --- | --- | --- | --- | --- |']
labels={'silent-footwork-block':'灵动步法/敏捷牌挡','silent-strength-weak-observation':'力量与虚弱覆盖','silent-deck-burst-observation':'能力/药牌取得与兑现','silent-vantom-slippery-growth':'滑溜逐击/毒限伤与准备成长','silent-fishing-rod-random-upgrade':'钓鱼竿随机升级'}
for c in C:
 e=c['after']
 if e['id'] not in labels:continue
 s=e['lesson'];reason=s.split('机制：')[1].split('决定胜负的战斗：')[0];case=s.split('典型案例：')[1];lines.append('| '+labels[e['id']]+' | '+reason+' | '+str(e['n_support'])+'/'+str(e['n_contradict'])+'；'+str(H[e['id']]['by_asc'])+' | '+case+' | '+e['id']+' |')
lines+=['','攻击滑溜支持11局，其中毒限伤8、准备成长11，逐帧子集索引见vantom-history；支持不是各组件使整场必胜的因果样本。钓鱼竿6支持局17次升级，普通战序号3/6/9/12按取得后计，F4/F13新局各一防御；不是核心步法已升级。力敏/敌增益可描述局部算式与威胁，替打法、单卡和路线整场胜因未控，统计/SL明确写观察。机制asc[0,20]；策略/统计原进阶范围保持，A10SL策略[10,20]、构筑/路线原A8+，不从低阶固定数值推A10。','','### 新增','','- 无，同主题并入原条目。','','### 更新','']
for c in C:lines.append('- '+c['id']+'：支持'+str(c['before']['n_support'])+'→'+str(c['after']['n_support'])+'，反例'+str(c['after']['n_contradict'])+'；加M0GY0A4M2F7H，更新案例/数字；账本'+','.join(M[c['id']])+'。')
lines+=['','### 退役','','- 无；没有本任务代码修复、反例超支持或新增高阶推翻。旧retired历史保留，无预算合并/压缩。','','### 和手写知识及代码冲突','','- 核静默其他8份JSON：boss-damage/boss-trust/double-boss/fight-value/fight-value-gates/monster-records/outcome-stats/room-costs，均为生成统计/模型/证据。文件来源/字段/SHA保留other-knowledge；不同截止点/模型预测不当机制反例，本局未到二三幕不改终局/双boss。需要修改的手写知识：无。','- 不改源码手写知识。滑溜攻击/毒已有0224/0227经验，0226已修漏毒bug没有重现，机制事实与purebug分账。SL原线失败后探索的实际血价属策略证据，独立strategy-proposal先核现行live实现/既有postmortem去重；本批未实现源码、不冒报代码shipped。','- 三独立提案：'+','.join(P)+'；source_task=experience-update/target_task=strategy-proposal，实际domains combat/potion/sl/structure，八改经验均关联本角色证据/层/轮/账本。无terminal参数变动或终局事实，不填terminal。','','### 代码问题（不给 DS）','','- 无新增纯bug；没有打法源码修复。本局完整dirty树、前五SL退出/未执行最少损失与毒、部分毛伤/幻象独立退场、逐房arrival表/时钟比、完整实际执行最优比例、未选路线/构筑/休息与单药时点整场对照、Jev实际缓存/费用均未记录，不用预训练补。','- 临时抽取第一次在prepare完成前启动update，缺rest-summary而失败，经验未写；等待prepare退出0后重跑。原帧核验初稿将StatusCard的null伤害参与乘法，修抽取脚本后585项通过。滑溜历史强化校验第一次子集计数不足，后补普通触媒2毒双结仅扣2、滑溜减2的独立窗口并分核轮初毒雾回补；失败日志/草稿全部留scratch，非游戏代码bug。','','### 测试','',f'- 原入口bash agent/tools/test-sandbox.sh，TMPDIR本scratch、PATH本机node、nice19/SANDBOX_WORKERS=1、固定数据。tsc {T["tsc"]}，vitest {T["files"]}文件/{T["cases"]}用例/退出{T["vitest"]}；'+('高负载超时后重跑，原失败日志保持。' if T.get('retry') else '完整入口未因失败重跑。')+'固定排除名单未变，不冒报沙箱外完整套件通过。','- JSON/唯一id/已有scope/中文name/角色12位局号/支持反例数/置信度/预算/原帧/历史及240前后切片通过；check-experience missing=[]/退出0、ledger.py check退出0、gitleaks/redact及git diff --check均0。','- 账本仅CLI：新增[]；proposed '+','.join(L['proposed'])+'；retired[]。九账本映射八经验，首证/prior/claim/原support/repeat/旧status/version历史保持，复盘未纳入的观察不改；实际shipped交运维据live完成事件核。','- live锁内：'+V['result']+'；刷新'+str(V.get('refresh'))+'；合前'+str(V.get('pre'))+'；实际合入'+str(V.get('merged'))+'。']
for c in V.get('conflicts',[]):lines.append('- '+c)
lines+=['- '+('未实际合入，不创建eval上线版本/规则上线通知；保留刷新数据、预检及源提交，依用户冲突流程停止，交调用方和运维兜底，不停对局。' if not V.get('merged') else '合后沙箱通过，实际eval/上线记录见live回执，源码提案未实现。'),'','### 切片大小','','- 固定种子20260929，从截至切点SILENT状态抽最高两阶A9/A10各20状态×6界面，共240前后配对；manifest保存池/UTC/唯一帧数，池不足仅有放回补足，不跨角色。CHARACTER=silent调用官方knowledge-slice.ts，common/silent/outcome冻结同份、仅换experience。','','| 进阶/界面 | 改前中位/最大 | 改后中位/最大 | 配对差中位 |','| --- | --- | --- | --- |']
for r in SS['rows']:lines.append(f'| {r["sample"]} | {r["before_median"]}/{r["before_max"]} | {r["after_median"]}/{r["after_max"]} | {r["paired_median"]} |')
s=SS['overall'];lines+=['',f'- 整体中位{s["before_median"]}→{s["after_median"]}（{s["median_change"]:+}字）；配对差中位{s["paired_median"]}；最大{s["before_max"]}→{s["after_max"]}，单片最大增加{s["max_increase"]}字。',f'- active{U["active"]}，正文{U["chars"]}字符，置信度{U["confidence"]}；A8适用{U["asc"]["8"]}；A9适用{U["asc"]["9"]}；A10适用{U["asc"]["10"]}。无需合并/压缩/预算调整，需要Roy定的规则：无。','','证据、脚本、CLI、提案、测试、原失败日志/初稿、合入回执及报告：'+str(O)+'。']
section='\n'.join(lines)+'\n';(O/'changelog-section.md').write_text(section);(O/'report.md').write_text(section)
if '--append' in sys.argv:
 path=ROOT/'paper/materials/experience-changelog-silent.md';before=path.read_bytes();assert ('## '+heading).encode() not in before
 with path.open('ab') as f:f.write(('\n'+section).encode())
 after=path.read_bytes();assert after[:len(before)]==before;(O/'changelog-append.json').write_text(json.dumps(dict(before_bytes=len(before),before_sha256=hashlib.sha256(before).hexdigest(),added_bytes=len(after)-len(before),heading=heading),ensure_ascii=False,indent=2)+'\n')
print('报告生成',len(section),'字符；append', '--append' in sys.argv)
