import json,subprocess
from pathlib import Path
O=Path(__file__).parent;ROOT=Path('/home/dw/Projects/agent-sts2');C=json.load(open(O/'changes.json'));CH=json.load(open(O/'cunning-history.json'));R={r['run_id']:r for r in json.load(open(O/'run-metadata.json'))}
def cli(command,rows,name):
 (O/(name+'-input.jsonl')).write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows));p=subprocess.run(['python3',str(ROOT/'learner/ledger.py'),command],input='\n'.join(json.dumps(r,ensure_ascii=False) for r in rows),text=True,capture_output=True);(O/(name+'-cli.log')).write_text(p.stdout+p.stderr);p.check_returncode();return p.stdout.strip()
first=min(CH['support'],key=lambda n:R[n]['ended']);cases={n:next(r for r in CH['cases'] if r['run']==n) for n in CH['support']}
new=dict(character='silent',kind='mechanic',by='learner:experience-update',first_run=first,prior='yes',prior_runs=[first],prior_note='最早SADL静默A7 F8 T1在任何本条学习前已实际饮用并获得三张升级刀；这是基本生成用法，模型缺口的prior=no及满手分支0257的unknown各自保持。',status='proposed',claim='静默9局42次已饮狡诈药水：手牌2—7张时37次各添三张升级小刀，8张时两次各添两张，满手10张三次不添。新增小刀基础6且升级，当前牌面攻击受现场力量/弱另改；满手分支仅WQZVENQ7DTRP。未有穿插用药整战胜线。',evidence=[dict(run=n,floor=cases[n]['floor'],turn=cases[n]['turn'],role='support',note='原始饮用后手位与新增升级小刀核对；'+('容量不足2/0/0及3/2/0仅本局' if n=='WQZVENQ7DTRP' else '支持有手位时新增3、基础6/升级状态')) for n in sorted(CH['support'],key=lambda n:R[n]['ended'])],where=dict(experience=['silent-cunning-potion-shiv-capacity']),note='首次生成事实与本次首次容量边界分开；silent-0256纯建模bug仍observed、silent-0257首次容量先验不改。')
newid=cli('add',[new],'ledger-new')
M={'silent-royal-poison-blood-vial-opening-net':['silent-0198','silent-0255'],'silent-footwork-block':['silent-0005'],'silent-strength-weak-observation':['silent-0006'],'silent-route-hp-observation':['silent-0019'],'silent-rest-buffer-observation':['silent-0020'],'silent-deck-burst-observation':['silent-0021'],'silent-noxious-fumes-growth':['silent-0011'],'silent-accelerant-triggers':['silent-0027'],'silent-afterimage-per-card-block':['silent-0023'],'silent-sai-start-block':['silent-0038'],'silent-ripple-basin-no-attack-block':['silent-0048'],'silent-wither-end-turn-loss':['silent-0024','silent-0059'],'silent-aeonglass-artifact-growth-sl':['silent-0025','silent-0079','silent-0228'],'silent-insatiable-dual-clock':['silent-0018','silent-0079'],'silent-well-laid-plans-retention':['silent-0030'],'silent-infested-prism-tainted-skill-cost':['silent-0168'],'silent-piercing-wail-temporary-strength':['silent-0046'],'silent-haze-group-poison-weak':['silent-0007'],'silent-reptile-trinket-temporary-strength':['silent-0063'],'silent-cunning-potion-shiv-capacity':[newid,'silent-0257']}
assert set(M)==set(C['added']+C['updated']);(O/'ledger-map.json').write_text(json.dumps(M,ensure_ascii=False,indent=2)+'\n')
cli('update',[dict(id=l,by='learner:experience-update',where=dict(experience=[e for e,ls in M.items() if l in ls]),note='第82次静默经验提交前链接，首证/先验/旧上线记录保持，独立strategy-proposal实现；无accepted/shipped。') for l in sorted({l for ls in M.values() for l in ls})],'ledger-prelinks')
common='''\n角色silent，仅已观察机制/进阶；所有evidence与反例分布见historical-facts.json和cunning-history.json。旧105局作历史核验，新两局作后期固定案例，同一战多试不当独立局；不既用本批拟合又宣称独立验证。首帧/最终退出HP净损、完整威胁与死亡截断分别算；未观察结算全序留未知。来源任务experience-update，实现任务strategy-proposal。\n\n固定验证只用本批已保存原始状态/动作与历史案例，不跑boss模拟池。本任务不改策略源码或依赖。独立任务先核现有实现；已等价须核实际live祖先源码才登记duplicate/implemented。证据不足保留现行为、waiting，完整未来整战验证按开始时间留出新局。Roy-2026-10-07-learning允许依据足够本人核验数据改旧规则，授权不提供游戏事实。其他角色及未观察进阶保持等价。实际规则上线先date并双通知Roy；回退恢复实现前源码，保留提案/原日志/失败历史。\n'''
groups=[('cunning-capacity',['combat','potion'],['silent-cunning-potion-shiv-capacity','silent-well-laid-plans-retention'],CH['support'],'''# 静默狡诈药水确定生成与保留容量提案\n\n旧行为：当前只读live的card-model.ts:1556—1558找不到POTION_EFFECTS返回null，combat-plan.ts:3159未纳入方案模型、:3844仍直接提供未知生成数饮用选项，满手续喝不能与出刀穿插共同比较。复盘原提案/0256保留，本任务不冒称已修。\n\n新行为：在证据覆盖的生成与容量分支中，用新增min(3,10−当前手牌)张升级小刀作为确定候选，基础伤6再按当前力/弱计算，消耗药瓶后手位/能量/HP分账；方案应能比较先出小刀再喝的合法完整顺序。WQZVENQ7DTRP A10 F33第5次T11八手三饮只添2/0/0，第6次五手添3/2/0；各实打12/30刀伤，满手耗瓶且HP/能量/敌血不变。第5次T8建立计划妥当，T9—11轮初十手。\n\n历史9局42饮，37次足够手位添3、2次八手添2、3次满手添0；所有新增刀upgraded=true、基础Damage6。SADL3CGYTGSR A7 F8 T1三手→六手、NB8KCF6HRGVF A10 F31 T5五手→八手。当前牌面4/7/8/9/10不当生成未升级反例，要核现场弱/力。容量不足仅本次一局，不推广所有生成牌。\n\n固定验证复现3/2/0新增、空位变化、升级状态、基础6及现场力量/弱；再测试饮用—出刀—饮用的完整动作序列和存档恢复，不定统一留药阈值。没有完整穿插用药胜局，不能声称多四刀可救本局，实施必须保持缺证据分支和其他角色等价。\n'''),
('mechanisms',['combat','potion'],['silent-footwork-block','silent-strength-weak-observation','silent-noxious-fumes-growth','silent-accelerant-triggers','silent-afterimage-per-card-block','silent-sai-start-block','silent-ripple-basin-no-attack-block','silent-wither-end-turn-loss','silent-infested-prism-tainted-skill-cost','silent-piercing-wail-temporary-strength','silent-haze-group-poison-weak','silent-reptile-trinket-temporary-strength'],['TXZ6RVMQA09D','WQZVENQ7DTRP'],'''# 静默持续能力、临时力量与分来源血价提案\n\n旧规则须核现有源码，不因已有公式重复改。新行为仅在存在缺项时按已核数字补同等条件的推演：步法普通2/升级3敏捷、能力不直接得挡、多牌基础加当前敏捷再核脆弱；临时减力/药后增力次轮撤，敌永久成长另核；余像逐后续出牌1、钗起7、水盆无攻击末4均不再次加敏捷。\n\nWQZVENQ7DTRP A10 F33六次T1双普通步法共4敏，防御9/生存者12/斗篷10，末T7共21对25实损4；T3尖啸临时0→−6令弱后23→18，22牌挡零损；T6敌力3中和后9×2无挡实损18。F25棱柱T1步法不添污染，两毒药技能添0→3→6且弱单击12→15→17；T3蛇咬/冒泡使三击6→9→12，26毒实扣26而零挡损36，T5火花3→6。技能毒/挡收益和逐击污染代价须同核，不一概禁技能。\n\nTXZ6RVMQA09D A10 F48末次T2暴露去3制品后可建弱；T5毒雾能力总5，T8补30→35、迷雾加4至39、触媒+建2后结39+38+37=114；T9三结120+直伤46至108，T10潜在126只扣剩108。末T10起钗7、防御5及余像1至13、无攻击水盆另4，两凋萎各12令11→4损7；毒杀没有免状态伤，内部结算先后未记录。三次T3虚弱药因爬行动物饰品给临时3力量，次轮撤，不能给毒伤加此力量。\n\n固定验收以上前后帧和历史公式/反例集，已有实现登记真实等价祖先，缺任何内部全序不凭预训练补齐。原方案抽牌重问前后不能沿旧整线预测，不将所有局部误差当纯bug，不拟合单卡胜率或固定出牌顺序。\n'''),
('continuation-sl',['combat','potion','sl','terminal'],['silent-royal-poison-blood-vial-opening-net','silent-aeonglass-artifact-growth-sl','silent-insatiable-dual-clock','silent-deck-burst-observation','silent-route-hp-observation','silent-rest-buffer-observation'],['TXZ6RVMQA09D','WQZVENQ7DTRP'],'''# 静默连战开场资源与SL同盘双向血价提案\n\n旧行为：已上线S1.double-boss1及S1.double-boss-phase1区分F48首胜/F49实际现场，不能再按“漏认连续boss”新增repeat。旧ROYAL_POISON+小血瓶只净失2、不足拆单件；现在新增无小血瓶净失4。\n\n拟议新行为：在实际观察且无未知回血/复活组合的分支，将每个新战斗出牌前4血价与下一战资源接续分列、确认可操作前的可用HP，不能预支用药/余像/毒雾或空奖励。TXZ6RVMQA09D A10 F43/45/46/48/49的70→66、52→48、62→58、60→56、4→0均出牌前；F48第三次T10毒杀留4、F49实验体111血22攻击未执行就死。小血瓶旧VPW8YH7A4QFM两次净2只保留组合值/未知顺序。不得放宽必死/SL规则：死亡风险来自实测入口，而未校准模拟1200首胜/1200后败仍不当证明。\n\nSL：TXZ三试第三次T6换冒泡+羽化比前次少损3/少扣9，后轮也变，首战胜但连战败；缺保持所有后轮固定的获胜对照。WQZVENQ7DTRP A10 F33第2/3次T9同指纹，26HP、敌184、4敏、同手/三药，侧步+逃离+防御换飞镖+侧步+逃离，实扣24/损13→扣39/损22，多15伤付9血，两候选模拟1200胜0，不能称同安全；末T7第二防御换逃离同扣24、损0→4、沙坑4→5，有延时收益不笼统禁逃离。末T11沙坑1、9血9挡对27、25毒结后敌56，实际HP9→0，攻击/沙坑先致死仍未知。\n\n固定验证须同时重现当轮血价/毒/沙坑/能力时点和首胜后入口，不能只排最长存活/最高伤。没有完整反事实，不定统一SL准入差额或药水持有阈值。路线/回复：旧105局七数组与分档逐行一致；WQ前场棱柱赢损64至16、猎人损21至10、盛碗虫损17，两餐券实补30、四火93、五SL恢复234独立列；TX五火102、事件休21/茶49、SL93分列。真实资源传递须保留封顶、增上限、空奖励和未知后场，不用异步生成表覆盖不同口径值。\n''')]
ids=[]
for name,domains,eids,runs,body in groups:
 lids=sorted({l for e in eids for l in M[e]});p=O/('proposal-'+name+'.md');p.write_text(body+'\n关联经验：'+','.join(eids)+'。\n关联账本：'+','.join(lids)+'。\n'+common)
 item=dict(character='silent',ledger=lids,runs=runs,source_task='experience-update',target_task='strategy-proposal',domains=domains,summary={'cunning-capacity':'狡诈药水确定生成与剩余手位、计划妥当保留容量及出刀穿插完整序列核验','mechanisms':'毒源/触媒、敏捷、临时力量和污染、牌挡/被动挡及凋萎血价分源核验','continuation-sl':'无小血瓶王室猛毒开场4血续战入口、SL同盘攻防/沙坑代价与真实资源结转'}[name],proposal=str(p.resolve()),experience=eids,rule_changes=True,authorization='Roy-2026-10-07-learning')
 (O/('proposal-'+name+'.json')).write_text(json.dumps(item,ensure_ascii=False,indent=2)+'\n')
 q=subprocess.run(['python3',str(ROOT/'learner/code_proposals.py'),'add','--character','silent'],input=json.dumps(item,ensure_ascii=False),text=True,capture_output=True);(O/('proposal-'+name+'-cli.log')).write_text(q.stdout+q.stderr);q.check_returncode();ids.append(q.stdout.strip());print(q.stdout.strip())
(O/'proposal-ids.json').write_text(json.dumps(ids,ensure_ascii=False,indent=2)+'\n')
