import collections,hashlib,json,subprocess
from pathlib import Path
O=Path(__file__).parent;ROOT=Path('/home/dw/Projects/agent-sts2');C=json.load(open(O/'changes.json'));A=json.load(open(O/'audit.json'));H=json.load(open(O/'historical-facts.json'));S=json.load(open(O/'slice-summary.json'));L=json.load(open(O/'ledger-result.json'));M=json.load(open(O/'live-merge.json'));T=json.load(open(O/'tests.json'));rest=json.load(open(O/'rest-summary.json'));sl=json.load(open(O/'sl-summary.json'));base=json.load(open(O/'baseline-check.json'));title=(O/'changelog-title.txt').read_text().strip();R={r['run_id']:r for r in json.load(open(O/'run-metadata.json'))}
stamp=subprocess.check_output(['date','+%Y-%m-%d %H:%M:%S %z'],text=True).strip()
lines=['','## '+title,'','### 来源','',f'- 记录时间{stamp}。只读notes/lessons.md:5392的MCT1GPTL8D35及11:52:31勘误、notes/run-1007-1123-MCT1GPTL8D35.md；runs.character=SILENT、A10/F42敗，无跳过。F23寄生惧魔ID采用PARAFRIGHT，54→46血量不变；last_seen按run-1007文件名取2026-10-07。', '- 开工exp-silent干净，git merge --no-edit main成功；README、最新STATE、决定末尾、学习协议、首次构建和最后两节方法已读。独立执行，不派agent、不运行play/boss模拟池、不联网、不推送。抽取/工具nice19单进程；测试固定沙箱入口。', '- 截至2026-10-07T03:22:52.000Z，89静默完局，A0—A10局数7/3/2/1/4/1/11/7/1/3/49。旧1324房78实际死亡，加新17房1死＝1341房79死；A10 49局627房49死。MCCK2602T1SR仍只进数字，不作新机制证据。无character旧局、其他角色、进行中及以后完局排除；本批是复盘证据全引擎口径，实际新局42次大脑均Codex，不替换爬塔战绩的纯Codex口径。', '- 沿第70节：首COMBAT至同房最终尝试末結算HP净损；死亡单列、负回复保留。Monster走廊与Unknown问号分开；入血/现场max HP分<25%、[25%,40%)、[40%,60%)、≥60%。REST/SHOP/普通EVENT按源入血关联下一更高层第一战，Ancient排除、多源可同战；回血后战按run/floor去重。TD1同房重启仍一房，SL不作独立局或回血；死亡余血截断不当完整需损，未结算毒不预支。cards/ends仍限定completed，实际派发逐帧另核。', '- 新抽696 decisions、42 brain、6 run-plans、7 sl-attempts；按时间二分seek流抽720静默帧，696决策逐帧匹配；同窗DeepSeek推理0。七尝试的逐轮需伤/扣血/玩家损失与原复盘完全一致；史莱姆首/第二T4完整combat相同、34血4能量，差8血价；末轮完整需损24、差17。', '- 旧88局抽取/分析重新执行，七数组、每档房局号/损值、节点转移、回血与SL逐行一致，没有上一节数字不一致。全部89局本角色日志和277段历史机制复盘重核；卡牌纳证局均核实际施放。原片段、seek偏移、代码、旧经验、历史进阶/支持/反例和切片均留learner/runs/20261007-121302-experience-update。', f'- 开工139 active/{C["old_chars"]}字<55000，不触发强制压缩。新增0、更新10（全補非药水证据、只改数字0）、退役0，139 active/{C["chars"]}字。十条旧逐局叙述压短为机制/一两个案例，完整旧文留experience-before.json；没有合并条目。potion:*及general:potion逐对象保持，其他旧含药句逐字保持，无新增或加强喝药规则。机制沿[0,20]，路线/休息/构筑观察沿[8,20]，狂战士高阶观察沿[9,20]，无新进阶策略反例。', '', '### 对照数据检查的主题','', '| 主题 | 数据 | 结论 |','| --- | --- | --- |', '| 角色/旧基线 | 旧88局七数组、血档、节点、回血和SL一致；新89局1341房79死 | 局/房/尝试分账，未结算与实死分开 |', '| 逐击力量/虚弱 | 沙虫T6力量3→−3，同有弱的两击9→4、总18→8；T7恢复3力、攻25 | 现场逐击算，临时减力不抹后轮成长；本局关键四场无玩家正力/敏 |', '| 尖啸 | 两试T6普通减6；胜试施放时余像另给1挡，敌HP127不变 | 减威胁与卡牌/被动挡分核，不当永久减力或伤害 |', '| 余像 | 胜试T7两逃离/两打击四牌0→1→2→3→4挡，25攻损21；整战63→9 | 逐牌实际兑现，不把建立或胜利归单能力 |', '| 毒刺/毒兑现 | 首试史莱姆T4直6、毒11→14另3，末8毒80→72未斩；沙虫胜T9 19毒截扣9、取消22攻 | 攻击/施毒/结算分列；不同来源毒合计不归单牌 |', '| 沙坑与攻击 | 沙虫首T7敌56、18血4挡对25差3读档；胜T7延长沙坑仍损21，T9余9毒杀胜 | 延长一条时钟不替代另一条时钟；非单变量整战 |', '| 狂战士同盘SL | 首/第二T4完整同combat，34血/4能，同扣52；防御换谋划专家挡8→0、损19→27；五轮两线24/24死 | 局部8血价成立，饱和死亡模拟不说明等价；四試0胜，没替线获胜实打 |', '| SL首抽序/赢次 | 沙虫两试1赢，初28顺序同、到手轮前10同；史莱姆四试0赢，初34顺序同、到手轮前18同 | 赢次余像/临时减力/毒已兑现，动作与后抽同变，不定运气或单能力胜因 |', '| 阳伞实到取得 | F37牌30→37、移除后36，三遗物、金币114保持；两条100金移除计划未派发 | 报价不计支出，未来商店不当实到；未外推药栏规则 |', '| 路线血量 | 三幕无精英，F35/38/39损11/1/39、F40回22至34，F42死；F39投影29而实51、F42投影35而实34 | 前房正偏差不能外推下一战安全，F43/47火与F45店未到 |', '| 实际回血 | F13/16/32/40合21+19+23+22=85；A10 276火187回血、实回4513、后战177/25死 | 回复增加当前缓冲，不保证后战；未选锻造无因果比较 |', '| 能力组合兑现 | 史莱姆四試建跟踪，仅第二建谋划专家，四試未建毒雾；末六轮扣209/需281、死余72 | 持有/施放/建立/收益分账；沙虫胜试跟踪未建立，不能预支能力 |', '| 组装师召唤/毒杀 | 本体155、T6剩4被7毒收掉，实损39；召唤改变总血池 | 召唤战不以全体剩血差算攻击毛伤，战末清爪不当逐只击杀 |', '| 模拟/时钟 | F16 736样本、日志胜率83.97%、赢损中位38.5，实异鱼9轮损42=1.09倍；F32 800样本低可信1.38%、中位56，实沙虫9轮损54=0.96倍 | 非同条件损血对照，不报校准误差；F29/40有效比较及逐轮时钟未记录 |', '| 药水边界 | 药水作用域逐对象/旧含药分句逐字保持，新增证据只用于非药水内容 | 不加证据局或使用规则 |', '', '七数组重算：','', '| 数组 | 改前 | 改后 | 旧行一致 |','| --- | --- | --- | --- |']
for key,x in base.items():lines.append(f'| {key} | {x["before"]} | {x["after"]} | 是 |')
lines+=['','A0—A9每格与第70节一致；完整局号、每房净损、所有进阶数据在audit.json。A10非空战房格（实死单列，活损中位含负回复）：','','| 幕 | 房型 | 血档 | 房/局 | 死/率 | 活场净损中位 |','| --- | --- | --- | --- | --- | --- |']
for x in A['bands']:
 if x['asc']==10 and x['n']:lines.append(f'| {x["act"]} | {x["type"]} | {x["band"]} | {x["n"]}/{x["runs"]} | {x["deaths"]}/{x["deaths"]/x["n"]:.2%} | {x["median_win"]} |')
lines+=['','A10源节点至下一实战（源入血档，多源可同战，Ancient排除）：','','| 幕 | 源房 | 血档 | 源节点/不同战 | 死/率 | 活场净损中位 |','| --- | --- | --- | --- | --- | --- |']
for x in A['transfers']:
 if x['asc']==10 and x['n']:lines.append(f'| {x["act"]} | {x["screen"]} | {x["band"]} | {x["n"]}/{x["unique_fights"]} | {x["deaths"]}/{x["deaths"]/x["n"]:.2%} | {x["median_win"]} |')
lines+=['','各进阶分母（SL不作独立局）：','','| 进阶 | 局 | 战房/死 | 火/回血/非回血 | 实回血 | 后战/死/活损中位 | 真重打场/尝试/赢尝试 |','| --- | --- | --- | --- | --- | --- | --- |']
for r,s in zip(rest,sl):
 fs=[f for f in A['fights'] if f['asc']==r['asc']];lines.append(f'| A{r["asc"]} | {r["runs"]} | {len(fs)}/{sum(f["death"] for f in fs)} | {r["rests"]}/{r["heal"]}/{r["smith"]} | {sum(r["gains"])} | {r["nexts"]}/{r["deaths"]}/{r["median"]} | {s["fights"]}/{s["attempts"]}/{s["wins"]} |')
lines+=['','- 真重打历史80场352试28赢→82场358试29赢；A10 47场211试16赢→49场217试17赢。本局两场六试一赢，另异鱼首试赢；4次读档＝沙虫1＋史莱姆3，predicted_death不当实际死亡。原sl-attempts的explore、decisions的sl_explore/sl_attempt以及draws、逐次需/扣/损均落盘。', '- 低血不同节点沿旧例复核：MGA0CZDDKC0P A10休息22→43后Monster损17活，4D4J8USKCPAV休息1→22后Monster损1活；D4LJ9QMGFB8Q事件13、BVF22RSFVBS9事件21后走廊死。新局F40 12→34后Monster死；不同敌人、构筑、入血及间隔混杂，仍是观察，没有改线/锻造受控因果。A8原一局9火8回血与7非回血包含同层其他动作，沿旧动作口径，不强令和等于房数。', '', '### 经验库自己带偏或写了没被执行的地方','', '- 同窗DeepSeek推理0，实际大脑42次全Codex；没有明确引用某经验id导致反向结果的原话，不由失败自动判路线/构筑repeat。兼容DeepSeek栏名不代实际引擎；以下为原文，原问答/journal留盘。', '- F34原话“阳伞免费补齐成长与防御，走三火无精英商店线。”（03:12:23.484Z）。F37确取货但毒雾在史莱姆四試均未施，F43/47火与F45店未到；免费取得与计划后续回复不能当现有成长/缓冲。0019/0021只补support，替路线/构筑胜负未记录。', '- F40原话“Heal to 34 HP. At 12 HP, projected hallway attrition is fatal; no upgrade compensates for that immediate risk.”（03:18:25.145Z）。12→34已执行、下一史莱姆死；未执行升级的整场结果不据此判休息错。', '- 已学SL血价仍被覆盖：03:20:12.040Z original“带毒刺击 -> 史莱姆狂战士, 防御+, 打击 -> 史莱姆狂战士, 投掷匕首 -> 史莱姆狂战士”改为“带毒刺击 -> 史莱姆狂战士, 谋划专家, 打击 -> 史莱姆狂战士, 投掷匕首 -> 史莱姆狂战士”；理由原文“the best untried line by the question\'s ranking, among those the rollout does not see dying more often”。同伤52多损8，0079原repeat保持。后续策略/抽牌也变化，不把全战败局单归该牌。', '- 末试T3在03:22:17.219Z将Jev的带毒刺击改end turn；第三/末次该轮实际扣27/15、都零损。明确原答最优不等最终完整执行，未换线整场实打未记录。', '', '### 机制推理','', '| 机制 | 推理 | 证据（支持/反例局数、进阶） | 典型案例 | 进了哪个条目 |','| --- | --- | --- | --- | --- |']
names={'silent-strength-weak-observation':'逐击力量/虚弱','silent-afterimage-per-card-block':'余像逐牌挡','silent-piercing-wail-temporary-strength':'尖啸临时减力','silent-poisoned-stab-components':'毒刺直伤/施毒/毒兑现','silent-insatiable-dual-clock':'沙坑与攻击双时钟','silent-berserker-growth-sl-observation':'同盘换成长血价观察','silent-lords-parasol-shop-acquisition':'阳伞实到库存取得','silent-deck-burst-observation':'能力组合实际兑现观察'}
E={e['id']:e for e in json.load(open(ROOT/'.worktrees/exp/knowledge/characters/silent/experience.json'))['entries']}
for eid,name in names.items():
 e=E[eid];lesson=e['lesson'];pre,case=lesson.split('典型案例：',1);case=case.split(' F33末次T4')[0] if eid=='silent-poisoned-stab-components' else case
 asc=','.join(f'A{a}:{n}' for a,n in H[eid]['asc_support'].items());lines.append(f'| {name} | {pre} | {e["n_support"]}/{e["n_contradict"]}；{asc} | {case} | {eid} |')
lines+=['', '- 全部12位evidence/contradicting及按进阶支持/反例见experience.json与historical-facts.json；卡牌支持局核到completed实用。全史实用余像24局199次、尖啸52局389次、毒刺54局1031次；纳证19/40/23局不同于全史分母。力量85/构筑84局是综合观察，不当每个子公式的独立实验数；败局机制成立不作反例，同局多次SL不多计支持。没有正力/敏建立的本局不加步法证据，没有毒雾施放不加该牌证据。药水只保留既有事实，不推使用规则。', '', '### 新增','', '- 无；本局主题并入已有条目，不重复建经验或账本。', '', '### 更新','', '| 条目 | 支持局数 | 字符改前→后 | 变化 |','| --- | --- | --- | --- |']
for x in C['diff']:lines.append(f'| {x["id"]} | {x["n_before"]}→{x["n_after"]} | {x["chars_before"]}→{x["chars_after"]} | 補MCT1GPTL8D35非药水证据、重算统计与压短旧案例 |')
lines+=['', '- 十条全补证，只改数字0；狂战士4→5支持且0反例，med→high，其余置信度按旧规则。没有条目合并；旧含药分句逐字保留、药水对象不动，更新旧逐局叙述均压成机制/一两个案例，原文保存在experience-before.json。', '', '### 退役','', '- 无；没有反例多于支持。本批未修代码；真实机制不因执行器已覆盖而退役，不把规划观察写成未修机制bug。', '', '### 和手写知识及代码冲突','', '- 静默另外七份boss-damage/room-costs/monster-records/outcome-stats/fight-value/fight-value-gates/boss-trust均为生成数据，无手写文件要改删。逐文件哈希/元数据留other-knowledge.json；room-costs截至88局、monster-records1325房窗比旧去重1324多TD1同房重启1，时间/窗口/战后回复口径差不判内容失效。本局新增17房留审计，不在本任务覆盖生成文件。boss-trust保留固定模型/切分/低可信标记，非新打法。common只定向核本局敌人HP/招式，不搬其他角色经验。', '- 当前combat-plan.ts已覆盖PIERCING_WAIL_POWER、AFTERIMAGE_POWER、STRENGTH_POWER/DEXTERITY_POWER和POISON_POWER，未见与本局实际数字冲突的手写知识；本任务不修改源码、生成器或铁甲行为。', '', '### 代码问题（不给 DS）','', '- 本局换线8血价是既有探索行为，0079 repeat留存，不重复开纯bug。末T6 least-loss预计−17与完整32−8=24、7血缺17一致；死亡截断7不误作完整只需7损。', '- 未记录：判死截断轮完整结算、召唤战全体毛伤/内部死亡先后、未选路线/休息/构筑和未换线受控整场结果、SL后完整最优原线执行比例、旧boss时钟每轮实估伤比、F29/40有效模拟比较、能力独立净胜率/伤害增量、Jev缓存。不从持有/评分、原答最优115/117、计划或最终输赢补造。', '', '### 测试','', f'- 源固定沙箱tsc{T["tsc"]}、vitest{T["vitest"]}、{T["files"]}文件{T["cases"]}用例；{T["note"]}。JSON、12位局号/角色/n/置信度/进阶/60000字预算、旧基线逐行、696决策状态匹配、同盘8血价、末需损24/缺17、历史实际施放、旧药对象/句子、git diff --check、提交前gitleaks均通过。固定排除名单/预算/依赖不改。', '- 只经learner/ledger.py/by=learner:experience-update，proposed '+','.join(L['proposed'])+'；新增/退役无，check0。十经验均有来源；0018补本局support，其余本局复盘已登记不重复加证据；原claim/first_run/asc/prior/support/repeat和版本历史保持，未纳复盘项/纯bug状态不动，不写accepted/shipped。主目录本节及账本只追加不提交，由调用方提交。', f'- live：实际合入{M.get("merged")}，合后测试{M.get("test_rc")}，刷新提交{M.get("refresh_commit")}，合前{M.get("base")}。'+M.get('reason','合入和合后沙箱通过。')+'；知识不同blob重叠：'+','.join(M.get('conflicting_overlap',[]))+ '。初步预检19处记录/论文数据冲突原件保留；最终锁内预检见merge-tree-locked.txt/live-merge.json，不覆盖、不硬解。', '- handoff-ops.md、源提交、账本映射及完成JSON交调用器experience-done通知运维核实际/兜底，只有实际合入才登记eval版本和shipped，完整沙箱外套件交调度器。未合入时本批没有上线记录/eval版本；不借上一批live测试宣称本批通过。不停对局、不运行play、不推送。', '', '### 切片大小','', '- 固定种子20260929，从截至本局的state.run.character_id=SILENT状态筛最高A9/A10，各20状态×COMBAT/REWARD/MAP/EVENT/REST/SHOP＝240配对。官方knowledge-slice.ts/CHARACTER=silent/setExperienceForTests，只换经验JSON，common及其他静默知识冻结；manifest/原切片留盘，不读其他角色或冒称V4整份前缀。', '', '| 进阶/界面 | 改前中位/最大（字） | 改后中位/最大（字） | 配对增量中位 |','| --- | --- | --- | --- |']
for x in S['rows']:lines.append(f'| {x["sample"].removeprefix("sample-")} | {x["before_median"]}/{x["before_max"]} | {x["after_median"]}/{x["after_max"]} | {x["delta_median"]} |')
lines+=['', f'- 配对增量中位{S["median_delta"]}字、最大增量{S["max_delta"]}字；总体中位{S["before_median"]}→{S["after_median"]}、最大{S["before_max"]}→{S["after_max"]}字。active139→139，{C["old_chars"]}→{C["chars"]}字，高69中44低26；A8 132条45855字，A9 133条46139字。需要Dai定的知识事项：无。']
text='\n'.join(lines)+'\n';p=ROOT/'paper/materials/experience-changelog-silent.md';before=p.read_bytes();assert ('## '+title).encode() not in before
(O/'changelog-section.md').write_text(text)
with p.open('a') as h:h.write(text)
after=p.read_bytes();assert after[:len(before)]==before and after[len(before):]==text.encode()
(O/'changelog-append.json').write_text(json.dumps(dict(before_bytes=len(before),before_sha256=hashlib.sha256(before).hexdigest(),append_bytes=len(text.encode()),append_sha256=hashlib.sha256(text.encode()).hexdigest(),title=title),ensure_ascii=False,indent=2)+'\n')
print('只追加完成',title,len(text.encode()),'字节')
