import json,subprocess
from pathlib import Path
O=Path(__file__).parent;ROOT=O.parents[2];LIVE=ROOT/'.worktrees/live';M=json.load(open(O/'live-merge.json'));L=json.load(open(O/'ledger-result.json'));C=json.load(open(O/'changes.json'));S=json.load(open(O/'slice-summary.json'));source=(O/'commit.txt').read_text().strip()
assert M.get('eval_version')=='S1.exp55' and M['merged'] and M['test_rc']==0
r=subprocess.run(['python3',str(ROOT/'learner/ledger.py'),'check'],text=True,capture_output=True);(O/'ledger-check-final.log').write_text(r.stdout+r.stderr);assert r.returncode==0
assert subprocess.check_output(['git','-C',str(ROOT/'.worktrees/exp'),'status','--short'],text=True).strip()==''
v=json.load(open(LIVE/'eval/versions.json'));assert sum(x['name']=='S1.exp55' and x['commit']==M['merged'] for x in v['versions'])==1
subprocess.run(['git','-C',str(LIVE),'merge-base','--is-ancestor',source,'HEAD'],check=True)
assert subprocess.check_output(['git','-C',str(LIVE),'rev-parse','HEAD:knowledge/characters/silent/experience.json'],text=True)==subprocess.check_output(['git','-C',str(ROOT/'.worktrees/exp'),'rev-parse','HEAD:knowledge/characters/silent/experience.json'],text=True)
stamp=subprocess.check_output(['date','+%Y-%m-%d %H:%M:%S %z'],text=True).strip()
closing=(f'本节收尾（{stamp}）：源{source}，实际live合入{M["merged"]}，上线登记{M["release_commit"]}，eval S1.exp55。源初轮及定稿均tsc0/vitest0、209文件2245用例；定稿因女王首试赢例四→五校正重跑，非失败/超时。合后tsc0/vitest0、{M["live_tests"]["files"]}文件{M["live_tests"]["cases"]}用例、首轮通过。新增0更新21（21补证、0纯数字）退役0，active126→126、55756→56138字，高58中41低27；A8 119条52862字/A9 120条53161字/A10 121条53741字。开工压5条1196字，旧文/数字/局号/证据/药水分句保持；240配对中位增量−9、最大6152→5748字。旧66局全部明细/血档/节点/回血/SL逐行一致，新67局1059房57实死。实验体六试0赢、五判死未结算不补死/毒；clean40同序但仅前7张同到手轮，新阶段旧毒清、玩家能力留，新212段实扣88仍124，末13血27挡对55差15，临时减力/敏捷与牌挡/被动分别计。羽毛7局55到火、石头8局80房，正充能添火1→6补证；已建组件/前场满血不等于后场输出或血池足够，无替路线/构筑/休息单因。账本新增/退役无、22项proposed为'+','.join(L['proposed'])+'，最终check0，首证/先验/claim/旧version/repeat保持，交运维据experience-done登记shipped，不另设审核。刷新提交'+M['refresh_commit']+'、合前'+M['base']+'，重叠/冲突0、其他知识blob保持；无源码/生成器/其他角色/手写知识变更、不重建，无新用药规则。完整外部套件交调度器，交接learner/runs/20261007-000343-experience-update/handoff-ops.md及完成回报通知运维；主目录本节/账本仅追加不提交，不停对局、不运行play、不推送。需要Roy定：无。')
(O/'changelog-closing.md').write_text(closing+'\n')
with (ROOT/'paper/materials/experience-changelog-silent.md').open('a') as f:f.write('\n'+closing+'\n')
mechs=[dict(name='力敏/激怒',id='silent-strength-weak-observation'),dict(name='灵动步法',id='silent-footwork-block'),dict(name='致命毒药',id='silent-deadly-poison-application'),dict(name='毒雾',id='silent-noxious-fumes-growth'),dict(name='触媒',id='silent-accelerant-triggers'),dict(name='实验体阶段',id='silent-test-subject-phase-reset'),dict(name='尖啸',id='silent-piercing-wail-temporary-strength'),dict(name='预判',id='silent-anticipate-temporary-dexterity'),dict(name='精准',id='silent-accuracy-shiv-scaling'),dict(name='遗忘之魂',id='silent-forgotten-soul-exhaust-damage'),dict(name='刀扇',id='silent-fan-of-knives-capacity'),dict(name='音叉',id='silent-tuning-fork-skill-block'),dict(name='钗/锚',id='silent-sai-start-block'),dict(name='光滑石头',id='silent-smooth-stone-opening-dexterity'),dict(name='永恒羽毛',id='silent-eternal-feather-rest-arrival-heal'),dict(name='南瓜蜡烛',id='silent-pumpkin-candle-charge-energy'),dict(name='同族观察',id='silent-kin-poison-sl-observation'),dict(name='女王观察',id='silent-queen-poison-main-target'),dict(name='构筑兑现观察',id='silent-deck-burst-observation')]
report=dict(task='experience-update',version='2026-10-07.1',commit=source,merged=M['merged'],added=0,updated=21,retired=0,active=126,mechanisms=[x['name'] for x in mechs],tests=dict(tsc=0,vitest=0,cases=M['live_tests']['cases']),ledger=L)
(O/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
handoff='\n'.join(['# 静默经验第55批运维交接','',f'- 任务20261007-000343-experience-update，证据ZVYUL2YP3518 SILENT A10及00:00:18 ID勘误，经验2026-10-06.29→2026-10-07.1。',f'- 源{source}（exp-silent），实际live合入{M["merged"]}，发布{M["release_commit"]}，唯一eval S1.exp55。',f'- 刷新{M["refresh_commit"]}在合前保留；知识重叠0、其他blob保持，source/live经验blob一致；没有源码/生成器改动。','- 源初轮及定稿tsc0/vitest0、209文件2245例；定稿仅四→五首试赢例校正后重跑。合后首轮tsc0/vitest0、'+str(M['live_tests']['files'])+'文件'+str(M['live_tests']['cases'])+'例。完整外部检查由本批调度器补跑。','- 账本22项仅proposed/check0；请据完成事件核实际合入后，经learner/ledger.py/by=ops登记本批shipped/S1.exp55，首证/先验/claim/证据/repeat/旧version历史保持：'+','.join(L['proposed'])+'。','- 新增0更新21均补证、退役0；active126/56138字，A8 119/52862、A9 120/53161、A10 121/53741。240切片配对中位−9、最大6152→5748。','- 旧66局完整重算一致；六试0赢、五判死未结算不补；clean40同序但只有前7张同到手轮。新67局1059房57死。新阶段清旧毒、留能力，13血27挡对55差15；无单项或运气胜因，无新用药规则/手写知识变化。','- 根目录experience-changelog-silent.md只追加本节和收尾；账本仅CLI追加，均未由本学习者提交，供调用方归档。所有原始分流/审计/临时抽数失败及修正/旧经验/压缩/切片/两次源检查与合后检查在本目录。','- 不停对局、不运行play、不推送；需要Roy定：无。'])+'\n'
(O/'handoff-ops.md').write_text(handoff)
for name in ['changelog-closing.md','handoff-ops.md','report.json']:
 with (O/('gitleaks-'+name+'.log')).open('w') as f:subprocess.run(['nice','-n','19',str(Path.home()/'.local/bin/gitleaks'),'dir','--redact','--no-banner',str(O/name)],stdout=f,stderr=subprocess.STDOUT,check=True)
print(json.dumps(report,ensure_ascii=False));print('上线登记',M['release_commit'],M['eval_version'])
