import json,re,subprocess,sys
from pathlib import Path
O=Path(__file__).parent.resolve();ROOT=Path('/home/dw/Projects/agent-sts2');LIVE=ROOT/'.worktrees/live';source,merged=sys.argv[1:3];C=json.load(open(O/'changes.json'));L=json.load(open(O/'ledger-result.json'));mapping=json.load(open(O/'ledger-map.json'));ids=json.load(open(O/'proposal-ids.json'));stamp=subprocess.check_output(['date','+%Y-%m-%d %H:%M:%S %z'],text=True).strip();p=LIVE/'eval/versions.json';v=json.load(open(p));n=max(int(m[1]) for r in v['versions'] if (m:=re.fullmatch(r'S1\.exp(\d+)',r['name'])))+1;name='S1.exp'+str(n)
v['versions'].append(dict(name=name,family='Silent',commit=merged,source=f'decision-log {stamp}（源{source}；静默经验2026-10-08.7、第90批KFRDELW2TH2P A10，增4改9退0，165 active/52792字；旧118局七数组逐行一致，奇巧限额/已核三药/触媒与现场力挡分账，跨幕13局19对。源及合后原沙箱0，仅知识前缀；三独立strategy-proposal pending，不当源码实现。）'));p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
subprocess.run(['git','-C',str(LIVE),'add','--','eval/versions.json'],check=True);diff=subprocess.check_output(['git','-C',str(LIVE),'diff','--cached','--binary'],text=True);scan=subprocess.run(['gitleaks','stdin','--no-banner','--redact'],input=diff,text=True,capture_output=True);(O/'gitleaks-publication.log').write_text(scan.stdout+scan.stderr);scan.check_returncode();subprocess.run(['git','-C',str(LIVE),'commit','-m','Register Silent experience 2026-10-08.7 deployment','-m','Co-Authored-By: Codex GPT-6 <noreply@openai.com>'],check=True);pub=subprocess.check_output(['git','-C',str(LIVE),'rev-parse','HEAD'],text=True).strip()
line=f'- {stamp[:16]} Codex学习者静默第90次经验实际上线：来源条目'+','.join(C['added']+C['updated'])+'；证据KFRDELW2TH2P/A10及条目已有本角色历史局；账本'+','.join(L['proposed'])+f'；源{source}、合入{merged}、发布{pub}/唯一{name}；经验2026-10-08.6→.7/增4改9退0/165 active/52792字，旧118局七数组/分档/回血/SL复算一致，源与合后原沙箱0；仅知识前缀，不改变其他角色，三份代码提案pending，运维据完成事件确认shipped及外部补测，学习者不标shipped。\n'
with (ROOT/'paper/materials/decision-log.md').open('a') as h:h.write(line)
notice=f'\n### {stamp} 静默经验 {name} 已上线，通知 Roy／运维\n\n来源任务experience-update/20261008-061302，证据KFRDELW2TH2P及关联历史静默局，源{source}；合入{merged}；发布{pub}；2026-10-08.6→.7。以下是知识前缀旧新表述，独立源码提案仍pending。\n\n'
for c in C['entries']:
 b,e=c['before'],c['after'];old=b['lesson'] if b else '原库无该独立条目';notice+=f'- {c["id"]}：旧规则/表述：{old}；新规则/表述：{e["lesson"]}；支持{e["n_support"]}/反例{e["n_contradict"]}、asc{e["asc"]}；证据'+','.join(c['new_runs'])+'；账本'+','.join(mapping[c['id']])+'。\n'
notice+='\n预期影响：路线/休息按赢战实际资源、既有能力与出牌额度核兑现；三药按实际剂量/触发条件分账，减少未知覆盖，不声称胜率提升、不新增固定早喝/留药/SL阈值。提案'+','.join(ids)+'交独立strategy-proposal。回退：只三方逆向恢复本次experience差量并登记新回退版本，保留知识刷新、并行代码/记录及证据/台账，不硬重置后续进展。完整旧新/测试/账本见本任务report.md/changes.json。\n'
for path in ['notes/for-roy.md','ops/inbox-dev.md']:
 with (ROOT/path).open('a') as h:h.write(notice)
(O/'publication.json').write_text(json.dumps(dict(source=source,merged=merged,publication=pub,version=name,ledger=L['proposed']),ensure_ascii=False,indent=2)+'\n');print(name,pub)
