import json,subprocess
from pathlib import Path
O=Path(__file__).parent;ROOT=Path('/home/dw/Projects/agent-sts2');new=(O/'ledger-new-cli.log').read_text().strip()
M={'silent-footwork-block':['silent-0005'],'silent-strength-weak-observation':['silent-0006','silent-0083'],'silent-route-hp-observation':['silent-0019'],'silent-rest-buffer-observation':['silent-0020'],'silent-deck-burst-observation':['silent-0021','silent-0125'],'silent-poisoned-stab-components':['silent-0007'],'silent-haze-group-poison-weak':['silent-0007'],'silent-ornamental-fan-attack-block':['silent-0088'],'silent-beckon-held-end-turn-loss':['silent-0176'],'silent-fysh-resource-sl-observation':['silent-0079','silent-0176'],'silent-speed-potion-temporary-dexterity':[new,'silent-0091']}
(O/'ledger-map.json').write_text(json.dumps(M,ensure_ascii=False,indent=2)+'\n')
rows=[dict(id=lid,by='learner:experience-update',where=dict(experience=[e for e,ls in M.items() if lid in ls]),note='第81次静默经验更新提交前关联；不改历史首证、先验或已上线记录，源码提案独立实现。') for lid in sorted({x for ls in M.values() for x in ls})]
(O/'ledger-prelinks-input.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows))
r=subprocess.run(['python3',str(ROOT/'learner/ledger.py'),'update'],input='\n'.join(json.dumps(r,ensure_ascii=False) for r in rows),text=True,capture_output=True);(O/'ledger-prelinks-cli.log').write_text(r.stdout+r.stderr);r.check_returncode()
common='''\n## 边界、时间切分与回退\n\n来源任务 experience-update；独立实现任务 strategy-proposal；角色 silent。公式只覆盖本角色已经观察的机制，数字按现场进阶及牌文核。旧104局作历史核验，本次KEN作为后期固定案例，六试只算一个局，不能既用KEN拟合又称它独立验证。其他角色及未观察进阶规则保持等价；本任务不改源码、依赖或运维提示。\n\n有足够本角色数据后可依据 Roy-2026-10-07-learning 修改现行人定规则；授权不提供游戏事实。先检查当前实现并用冻结帧核对，如已等价须核实际live祖先源码才可登记duplicate/implemented，缺可重放状态或完整反事实则waiting。新规则参数需要更早独立局训练、按开始时间留之后新局验证，本批不拟合通用血价或预报胜率。独立实现按原沙箱入口自测；实际上线后先date，再双通知Roy旧/新规则、局号/账本/任务、预期影响与回退。回退恢复实现前源码，保留原提案、日志和失败历史。\n'''
groups=[('mechanisms',['combat','potion'],['silent-footwork-block','silent-strength-weak-observation','silent-poisoned-stab-components','silent-haze-group-poison-weak','silent-ornamental-fan-attack-block','silent-beckon-held-end-turn-loss','silent-speed-potion-temporary-dexterity'],'''# 静默猎手敏捷、力量、被动挡、毒和持牌失血的代码核验提案\n\n## 已核实证据与分母\n\nKEN58SH9SLZ6 A10：F17末试T8两防御各5，T9普通步法才建2敏，T10/12防御各7，T13无挡牌；F5 T2速度药增5敏使斗篷6→11、对8+4损1，T3撤去。历史32局38饮均当步敏捷及速度层+5；35次次轮净撤5，53FL/G403/DPY三次有独立步法、口红或预判改变敏捷，速度层同样消失。首证C48LLXBGKXQ9 A0 F12 T2药后防御7→12且实放，下一轮7→2；1LMBFGSMCWKU A4 F48 T6已有3敏且脆弱，药后8敏使防御/残影各6→9，不能直接在折减牌面加5。全部逐局及反例集合在speed-history.json，反例0。\n\nKEN F5 T3/4/5仪式2令力量2/4/6、同招13/15/17，虚弱不取消持续成长；这只支持仪式/力量一般关系，不给雕刻师专属9层条目追加未遇敌局。F17末试T2第三攻击中和后挡0→4、T3小刀6→10，折扇与尚未建立的步法分账。T6迷雾当步给4毒、本体HP不变；T8刺击直伤6、毒5→8结8合14，T10无实体6毒只扣1。末T6无敌攻击仍因一呼唤61→55失6；T10攻击15减挡7加呼唤6合14，T12手空仅20−7=13。上述机制各条历史支持局与进阶在historical-facts.json；不把整战死亡当公式反例。\n\n## 旧规则、新行为与固定验证\n\n本树card-model.ts:1047已读取步法动态敏捷；:1221速度药仍注“STS1估计”，观察现在足够支撑已见+5与期限，但注释不能当游戏证据。先核现有方案内和后轮推演是否保持当轮卡牌挡、脆弱逐牌取整、临时/常驻敏捷与折扇分源。拟议只在缺项时依据这些实盘补等价公式；例如药不能回补已经获得的挡，次轮必须撤其5层而保留独立能力，折扇4不能再次加敏捷。\n\n同时核HAZE施毒/弱与逐次结束毒结算、无实体逐击限伤、BECKON每张6先行失血；当前已有实现则登记真实祖先，不再重复改。固定验证须复现KEN各数字及1LMB脆弱组合，附原题面与续步，防止把追加小刀多1伤认模型差错。没有单牌提前施放/不喝药的受控整战，暂不改变固定顺序、饮用或持有阈值。\n'''),
('sl-cost',['combat','sl'],['silent-fysh-resource-sl-observation','silent-deck-burst-observation','silent-beckon-held-end-turn-loss'],'''# 静默猎手异鱼同盘SL血价与能力兑现窗口提案\n\n## 证据和相反取舍\n\nKEN58SH9SLZ6 A10 F17第4/5试T10决策指纹相同，37血、敌82血且无实体，原呼唤/刺击/呼唤，第5试匕首雨替第二呼唤：实伤2→4、净损15→21，持牌多6换仅两段各1。B2 .385→.127、配对差−.2583、标准误.0132，五轮死亡6/24→12/24。第4试T15、第5试T13判死，但后轮动作亦变，不能证明这一步独自导致整战早死。\n\n反向取舍：第4/末试T5同指纹，突然一拳替步法省2血、追加小刀后实伤1→2，但能力T5延到T9，T8双防御仍各5；这是反驳“只保血恒优”的案例，并不反驳条目所写双向成本。第2试T2唯一HP护栏换迷雾为匕首雨+呼唤，省10血多4即时伤而不建4毒，原线未完整实打、长期代价未知。\n\n三场A10重打：2Y27VAYZDA02四试第4胜、751FN9QM9MHQ与KEN各六试全败，合16试1赢。2Y27胜次处理呼唤后毒杀保2血，但后抽与动作同变，既不独立归单步也不归运气。KEN末试前四轮扣85、13轮扣186仍余35，6血0挡对中和后的9死；计划毒雾/毒药/触媒都未取得，能力长期分数不能预支成当前挡。\n\n## 旧规则、新行为、验证及限制\n\n当前explore.ts:1507—1508在未启notWorseOnly时仍从B2更差的未试线探索，这是既定规则，不按纯bug处理。拟议独立任务先核选择的结构化代价：持牌失血、无实体新增实伤、能力建立时点、配对差及误差，保留原题/最终替换/续问完整结果。再验证在已观察的呼唤+无实体局面如何并用血价与后续窗口排序，而不是只按未试或最少失血。\n\n固定重放须复现T10的2/15与4/21、T5省2但敏捷延到T9、T2取消4毒；当前没有保持其余后轮不变的胜局，不能拟合统一6血/2伤准入阈值或直接关闭探索。缺完整可重放后续须waiting并保留现规则。新局验证足够后再按授权修改排序；不承诺本局因此可赢。\n'''),
('resources',['potion'],['silent-route-hp-observation','silent-rest-buffer-observation'],'''# 静默猎手赢战耗药、真实回复与下一战资源核验提案\n\n## 证据与统计口径\n\nKEN58SH9SLZ6 A10 F3 T2攻击药、F4 T1稳定、F5 T2速度、F11 T1虚弱/T2攻击、F15 T1发光/技能，共7独立获药7饮0弃，boss六试空栏。六赢战净损0/3/0/37/6/0合46；F5 53→16的37不可因获胜漏记，F15零损不等没有花药。F12加湿器26/76→53/81补27、F16 46/81→75/86补29，事件补16、潜水付7、五次SL恢复348单列。\n\n105静默完局逐阶统计，A10 65局354火/245回血5826，去重227下一战36实死、活损中位24。Monster走廊与Unknown问号战分开，死亡单列、首战HP减最终结算HP、负回复保留；REST/SHOP/普通EVENT入血比例四档关联下一更高层第一战。未走精英线没有实际结果，改无精英与两次回血不作为错误。\n\n## 旧行为、新行为与验证\n\n现饮用/持有价值规则暂保留。本提案先要求独立任务核药水候选与实际槽位/HP/能力变化的一致性、由前序赢战到boss入口的资源结转。SL恢复不当新获药/路线回血，零损的已喝药战不当未喝也零损，未来营火不预支为现在HP；如当前已经正确则核祖先登记等价，不改代码。\n\n固定验证复現7个饮用动作、两次真实回复及六次入口。对F15不饮用/七药留boss缺受控整战，不能据本局设置固定留药阈值或承诺换路线获胜。以后用历史独立局训练、新局时间留出验证，再决定资源预算调整；本批只保留实际行为与限制。\n''')]
ids=[]
for name,domains,eids,body in groups:
 lids=sorted({l for e in eids for l in M[e]});path=O/('proposal-'+name+'.md');body+='\n关联经验：'+','.join(eids)+'。\n关联账本：'+','.join(lids)+'。\n'+common;path.write_text(body)
 runs=json.load(open(O/'speed-history.json'))['support'] if name=='mechanisms' else ['KEN58SH9SLZ6']
 row=dict(character='silent',ledger=lids,runs=runs,source_task='experience-update',target_task='strategy-proposal',domains=domains,summary={'mechanisms':'核验已观察敏捷/临时撤层、仪式力量、折扇被动挡、毒与呼唤血价；缺项才补公式，已等价核真实祖先','sl-cost':'异鱼同指纹SL并核持牌血价、无实体实伤与步法建立窗口；完整反事实不足保留探索规则','resources':'核赢战耗药与真实回复到boss入口的资源结转；缺未饮用/留药整战对照保留现价值规则'}[name],proposal=str(path.resolve()),experience=eids,rule_changes=True,authorization='Roy-2026-10-07-learning')
 (O/('proposal-'+name+'.json')).write_text(json.dumps(row,ensure_ascii=False,indent=2)+'\n')
 r=subprocess.run(['python3',str(ROOT/'learner/code_proposals.py'),'add','--character','silent'],input=json.dumps(row,ensure_ascii=False),text=True,capture_output=True);(O/('proposal-'+name+'-cli.log')).write_text(r.stdout+r.stderr);r.check_returncode();ids.append(r.stdout.strip());print(r.stdout.strip())
(O/'proposal-ids.json').write_text(json.dumps(ids,ensure_ascii=False,indent=2)+'\n')
