#!/usr/bin/env python3
"""Measured HP change per map room -> src/knowledge/room-costs.json (the route facts' HP projection).

For every logged run, the HP on the last MAP frame of floor f-1 (the HP the room of floor f was entered
with) minus the HP on the first MAP frame of floor f (after that room: fight, Burning Blood, event, rest,
potions drunk in it), keyed by ascension, act (floors 1-17 / 18-33 / 34+) and the room's map type
(Monster, Elite, Unknown, RestSite, Shop, Treasure). Positive = HP lost. Rooms that crossed an act or
ended the run (death) have no next MAP frame and are not counted, so fight costs are survivors' costs.

Output: {"meta": {...}, "by_asc": {"8": {"2": {"Monster": {"n", "median", "p75", "mean"}, ...}}}}.

Usage:
  python3 tools/build-room-costs.py [--logs DIR] [--out PATH]
Refresh (after new runs): python3 tools/build-room-costs.py   (seconds: only MAP frames are parsed)
"""
import argparse
import collections
import json
import os
import statistics
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(ROOT, "src", "knowledge", "room-costs.json")
MAP_MARK = b'"screen":"MAP"'


def act_of(floor):
    return 1 if floor <= 17 else 2 if floor <= 33 else 3


def quantile(values, p):
    xs = sorted(values)
    k = (len(xs) - 1) * p
    i = int(k)
    j = min(i + 1, len(xs) - 1)
    return xs[i] + (xs[j] - xs[i]) * (k - i)


def scan(states_path):
    """run id -> floor -> {first, last, type, asc} from the MAP frames."""
    runs = collections.defaultdict(dict)
    first_ts = last_ts = None
    with open(states_path, "rb") as handle:
        for line in handle:
            if MAP_MARK not in line[:4000]:
                continue
            try:
                row = json.loads(line)
            except ValueError:
                continue
            state = row.get("state") or {}
            if state.get("screen") != "MAP":
                continue
            run = state.get("run") or {}
            floor = run.get("floor")
            run_id = state.get("run_id")
            hp = run.get("current_hp")
            if floor is None or hp is None or not run_id or run_id == "run_unknown":
                continue
            first_ts = first_ts or row.get("ts")
            last_ts = row.get("ts") or last_ts
            themap = state.get("map") or {}
            current = themap.get("current_node") or {}
            room = None
            for node in themap.get("nodes") or []:
                if node.get("row") == current.get("row") and node.get("col") == current.get("col"):
                    room = node.get("node_type")
                    break
            mark = runs[run_id].setdefault(floor, {"first": hp, "last": hp, "type": room, "asc": run.get("ascension")})
            mark["last"] = hp
            mark["type"] = room or mark["type"]
    return runs, first_ts, last_ts


def build(runs):
    losses = collections.defaultdict(list)
    for floors in runs.values():
        for floor, mark in floors.items():
            before = floors.get(floor - 1)
            if not before or mark["type"] is None or mark["asc"] is None or act_of(floor) != act_of(floor - 1):
                continue
            losses[(str(mark["asc"]), str(act_of(floor)), mark["type"])].append(before["last"] - mark["first"])
    by_asc = {}
    for (asc, act, room), values in sorted(losses.items()):
        by_asc.setdefault(asc, {}).setdefault(act, {})[room] = {
            "n": len(values),
            "median": round(quantile(values, 0.5), 1),
            "p75": round(quantile(values, 0.75), 1),
            "mean": round(statistics.mean(values), 1),
        }
    return by_asc


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--logs", default=os.path.join(ROOT, "logs"))
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()
    started = time.time()
    runs, first_ts, last_ts = scan(os.path.join(args.logs, "states.jsonl"))
    out = {
        "meta": {
            "note": "Generated by tools/build-room-costs.py from logs/states.jsonl MAP frames. HP lost in each map room "
            "(entry HP minus HP on the next floor's first MAP frame; negative = healed), by ascension, act and room type. "
            "Rooms that ended the run (deaths) or crossed an act are not counted.",
            "runs": len(runs),
            "first_seen": first_ts,
            "last_seen": last_ts,
        },
        "by_asc": build(runs),
    }
    tmp = args.out + ".tmp"
    with open(tmp, "w", encoding="utf8") as handle:
        json.dump(out, handle, indent=1, sort_keys=True)
        handle.write("\n")
    os.replace(tmp, args.out)
    print(f"room costs: {len(runs)} runs -> {args.out} ({time.time() - started:.1f} s)", file=sys.stderr)


if __name__ == "__main__":
    main()
